### PR TITLE
Enables the override of the WaitForUI5 timeout

### PR DESCRIPTION
**Pull request by ArnaudBuchholz**
I need guidance on how to document & test

### CODE REVIEW

**Comment by vobu** [comment]
i'll do my best, currently short on time → please be patient until the beginning of next week 🙏

**Comment by dominikfeininger** [comment]
Hi @ArnaudBuchholz, nice contribution. Looks good to me at the first glance.

Documentation might be here: 
https://github.com/js-soft/wdi5/blob/develop/README.md#usage
and here
https://github.com/js-soft/wdi5/tree/develop/wdio-ui5-service#installation
the best places to the two parts.

Usually we have a wdi5 test for each functionality. In the `wdio-ui5-service` part the test run against the openui5 SDK site. I can hardly imagine a testcase for this scenario.

**Comment by ArnaudBuchholz** [comment]
@dominikfeininger Documentation added
@vobu

**Comment by ArnaudBuchholz** [comment]
@dominikfeininger @vobu Anything else you are waiting from me ?

**Comment by dominikfeininger** [comment]
Hi @ArnaudBuchholz, sry for the delay. I will try to review today.

**Pull request merged**
