### PR TITLE
Fix WDI5 for Fiori 1.60

### PR DESCRIPTION
**Pull request by nilskasseckert**
Good Morning @vobu @dominikfeininger ,

I started to fix some stuff for Fiori 1.60

Currently I have a problem in the generated-methods.test.js

I always get: `stale element reference: element is not attached to the page document`

Would be nice if you can have a look.

Thanks!

### CODE REVIEW

**Comment by nilskasseckert** [comment]
Good morning @vobu ,

just so we don't misunderstand each other. Are you developing this further or am I? 

If you are: Is there a rough roadmap until when? I know you guys are doing this voluntarily and I really appreciate it. I'm just asking so we can plan on our end.

**Comment by dominikfeininger** [comment]
Hi, I started on the weekend, but wasn't able to finish. I will try to push a first version today.

**Comment by dominikfeininger** [comment]
Hi, created a branch https://github.com/js-soft/wdi5/tree/cleanupVersionCheck 
- I transferred your navigation fix 👍
- Wasn't able to reproduce the finding you had https://github.com/js-soft/wdi5/issues/76#issuecomment-818740573 with the _'This is an array in array in a array'_ But already marked it as `TODO:`

Please have a look if the features and fixes work for you. The included self tests can now be executed with version UI5 1.60.35. 

`wdio-ui5.conf.js` append the UI5 Version to `baseUrl` eg. https://openui5.netweaver.ondemand.com/1.60.35/
`npm run test_ui5`

**Comment by nilskasseckert** [comment]
Good morning,

thanks for your effort but I can not see any changes compared to to my branch before. If I execute the multi version tests with all tests

```
`specs: [path.join('test', 'ui5-app', 'webapp', 'test', 'e2e', 'basic.test.js'), path.join('test', 'ui5-app', 'webapp', 'test', 'e2e', 'aggregation.test.js'), path.join('test', 'ui5-app', 'webapp', 'test', 'e2e', 'hash-nav.test.js'), path.join('test', 'ui5-app', 'webapp', 'test', 'e2e', 'interaction.test.js'), path.join('test', 'ui5-app', 'webapp', 'test', 'e2e', 'list-interaction.test.js')]`
```

Still most of the tests fails. And the multiversion tests what we use.

Regards,
Nils

**Comment by dominikfeininger** [comment]
Hi, I will have a look on these issues this weekend.

**Comment by vobu** [comment]
hi @nilskasseckert - just FYI: after many painful debug sessions (for @dominikfeininger 🤣 ), we identified at least part of the root cause: in UI5 <= 1.60.x, the UI5 framework re-renders controls even on minor property changes.
Example: `$input.setEnabled(false)` causes a re-rendering (instead of a proper re-hydration) of the view.
This results in a _changed DOM node id_ in Webdriver.IO, which in turn cuts the "connection" of that UI element to its' `wdi5` representation. This in turn leads to a stale element reference, so the next time `wdi5` tries to operate on that UI element, it crashes.
Plan now is to incorporate a workaround into `wdi5` core:
- pass [`forceSelect: true`](https://github.com/js-soft/wdi5#control-selectors) through to the [UI5 method proxy](https://github.com/js-soft/wdi5#all-ui5-controls-native-methods)
- for UI5 <= 1.60.x, explicitly get ourselves a new `wdi5` representation of the Webdriver.IO-element in the [proxied UI5 control method](https://github.com/js-soft/wdi5/blob/276ff6d7d4557d981430dd750ca5614986ceca4f/wdio-ui5-service/src/lib/WDI5.js#L167) when `forceSelect: true` is set

-> this should be minimal invasive for both the tests and the core, meaning you'd have to (almost generically) use `forceSelect: true` in your selectors when running `wdi5` against a UI5 app using UI5 <= 1.60.x

we'll try and provide a working example in this branch throughout the next days

**Comment by nilskasseckert** [comment]
Wow thanks for your effort!! 

So if I use forceSelect everywhere it should work, correct?

Regards,
Nils

**Comment by vobu** [comment]
yep, after our fix is in place - and note the "should" part as our plan to fox things might still fail ™

**Comment by dominikfeininger** [comment]
Hi @nilskasseckert, please find the changes in branch https://github.com/js-soft/wdi5/tree/cleanupVersionCheck. The "gernerated-methods" test with UI5 version 1.60.33 run green. Please add the properties 
`wdi5Selector.forceSelect = true;`
and
`wdi5Selector.selector.interaction = 'root';`

Please confirm this solves the issue, then we will distribute a new version.

**Comment by nilskasseckert** [comment]
Hi @dominikfeininger,

thanks a lot for your effort! Almost everything works as expected. Thanks a million!

Only in the fixed navigation coding, the return value must be changed to the following:
`return sapUIVersion < oldAPIVersion ? hashChanger.getHash() : hashChanger.hash;`

In the hash-nav-test the test "should navigate to Main view via #/" fails. With navigation via #/ nothing happens. But this is not the big problem for us now.

Thanks for the adjustments! If this is in the master, we can use this internally directly.

Regards,
Nils

**Comment by dominikfeininger** [comment]
Hi, included your suggestion in the branch. Ia also fixed a navigation issue right away. PR https://github.com/js-soft/wdi5/pull/79 @vobu pls. review PR and create new version.

**Comment by nilskasseckert** [comment]
Hi @dominikfeininger ,
I will close this PR as you have opened a new one. Hopefully you can merge soon and we can use it.

Regards,
Nils

**Pull request closed without merging**
