### PR TITLE
feat: support FE testing library

### PR DESCRIPTION
**Pull request by vobu**
supersedes #155

### CODE REVIEW

**Comment by nlunets** [comment]
@vobu this works fine as it is on my machine so whatever it is, it's related to your build setup ;?

**Comment by vobu** [comment]
> @vobu this works fine as it is on my machine so whatever it is, it's related to your build setup ;?

catching up on this, I merged the latest `main` into this PR and indeed it seems to be mainly an issue w/ the 15 sec timeout. I'll bump that one and keep my fingers crossed 🤞

**Comment by vobu** [comment]
> > @vobu this works fine as it is on my machine so whatever it is, it's related to your build setup ;?
> 
> catching up on this, I merged the latest `main` into this PR and indeed it seems to be mainly an issue w/ the 15 sec timeout. I'll bump that one and keep my fingers crossed 🤞

bäm → tests 🟢! 
assigning the review to @Siolto as he's closest to the subject matter.
then this will go in!

**Review by Siolto — APPROVED** [review]
Fine for me 👍 🚀

**Pull request merged**
