### PR TITLE
feat: using custom waitForUI5 with callbacks instead of Promises

### PR DESCRIPTION
**Pull request by edvardas-kireilis**
There is ~1.2sec delay on every sap.ui.test.waitForUI5() function call since the call adds unresolved promise into _promiseWaiter pipeline. This change skips extra Promise creation to speed up waitForUI5() function execution

### CODE REVIEW

**Comment by edvardas-kireilis** [comment]
There is one consideration to think of.

**Comment by vobu** [comment]
just wanted to leave the comment here that I'm really looking forward to this PR. 
It will be a major improvement - thanks for all the work you put in so far 👍

**Comment by edvardas-kireilis** [comment]
I will leave it to you guys to decide if you want this change now. Tomorrow I will look into why tests are failing

**Comment by edvardas-kireilis** [comment]
This PR looks messy. Created a new one:
https://github.com/js-soft/wdi5/pull/217

**Pull request closed without merging**
