### PR TITLE
fix: control getShorthand returns array-valued property

### PR DESCRIPTION
**Pull request by ph-alsvik**
Very simple fix to when get$Shorthand-method returns a control prop that is an array of values (for example when calling getSelectedKeys on a MultiComboBox-control which returns an array of strings).

Please correct me on this, but AFAIK there is no way of knowing from the get$Shorthand what kind of return value is expected, other than calling the method and inspecting the returned value. This creates an edge case when the array is empty, because we don’t know if its an array of aggregates or js primitives. Therefore I’ve created a separate case “empty” for when the the returned value is an empty array, and warn the user that there is no data found in prop or aggregation.

Perhaps there is a more elegant way to address this issue?

### CODE REVIEW

**Comment by vobu** [comment]
Hi @ph-alsvik  - changes look good to me! 
As you stated, I also don't see a way of "forecasting" the return value of a `get$Shorthand` UI5 control's method.
So your solution makes sense and we'd like to get it in.
Any chance you could add a dedicated test for `Strings[]` and `empty` in `/examples/ui5-js-app/webapp/test/e2e/**/*.test.js`?

**Comment by vobu** [comment]
Hi @ph-alsvik  - changes look good to me! 
As you stated, I also don't see a way of "forecasting" the return value of a `get$Shorthand` UI5 control's method.
So your solution makes sense and we'd like to get it in.
Any chance you could add a dedicated test for `Strings[]` and `empty` in `/examples/ui5-js-app/webapp/test/e2e/**/*.test.js`?

**Comment by vobu** [comment]
ps: happy to blueprint a test case if needed. 
and also would like to direct your attention to #191 - we'll tame that beast soon :)

**Comment by vobu** [comment]
ps: happy to blueprint a test case if needed. 
and also would like to direct your attention to #191 - we'll tame that beast soon :)

**Comment by ph-alsvik** [comment]
Hi @vobu ! Sure, I'll make a test. Should have to add in the MultiComboBox control to the ui5-js app, right?

**Comment by vobu** [comment]
> Hi @vobu ! Sure, I'll make a test. Should have to add in the MultiComboBox control to the ui5-js app, right?

yep, exactly! just put it any place, layout is not the primary concern here 🤣

**Comment by ph-alsvik** [comment]
Hope this test covers it! Just let me know if I should alter it :)

**Comment by vobu** [comment]
> Hope this test covers it! Just let me know if I should alter it :)

will do! 
and thanks for the PR!
the tests will fail, as we're currently working on getting a `semver` comparisons right in oder to cope with UI5 1.100 - 
i will let you know once our enhancements are in so you can re-merge the then most recent `main` into your PR

**Comment by vobu** [comment]
> > Hope this test covers it! Just let me know if I should alter it :)
> 
> will do! and thanks for the PR! the tests will fail, as we're currently working on getting a `semver` comparisons right in oder to cope with UI5 1.100 - i will let you know once our enhancements are in so you can re-merge the then most recent `main` into your PR

`semver` fix now in `main` → please merge `main` again into your PR and let'em tests run :)

**Comment by ph-alsvik** [comment]
> semver fix now in main → please merge main again into your PR and let'em tests run :)

Hi @vobu! Hope I did everything right (fairly new to Git).

**Comment by vobu** [comment]
> > semver fix now in main → please merge main again into your PR and let'em tests run :)
> 
> Hi @vobu! Hope I did everything right (fairly new to Git).

you're doing great then!
there are still merge conflicts in 
- client-side-js/executeControlMethod.js
- examples/ui5-js-app/webapp/controller/Main.controller.js
- examples/ui5-js-app/webapp/model/countries.json
- examples/ui5-js-app/webapp/view/Main.view.xml

Please look through them and make sure, none of the recent changes in `main` break your enhancements.
Then once the tests go green, let's get your thingie in!!!

**Review by vobu — APPROVED** [review]
excellent 🤝

**Pull request merged**
